from __future__ import annotations

from typing import Protocol, Any


class VehicleApiClientPort(Protocol):
    async def get_status(self) -> Any: ...
    async def get_lidar_data(self) -> Any: ...
    async def reset(self) -> Any: ...
    async def steer(self, value: int) -> Any: ...
    async def throttle(self, value: int) -> Any: ...
    async def get_object_position(self, object_id: int) -> Any: ...
    async def move_object(self, object_id: int, x: int) -> Any: ...
